import type { Product, Category } from "./types"

export const categories: Category[] = [
  { id: "clothing", name: "服装" },
  { id: "electronics", name: "电子产品" },
  { id: "home", name: "家居" },
  { id: "beauty", name: "美妆" },
  { id: "sports", name: "运动" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "时尚连帽卫衣",
    description: "舒适保暖的连帽卫衣，采用优质面料制作，适合日常穿着。",
    price: 199,
    image: "/placeholder.svg?height=400&width=400&text=连帽卫衣",
    category: "clothing",
    categoryName: "服装",
    stock: 50,
  },
  {
    id: "2",
    name: "无线蓝牙耳机",
    description: "高品质无线蓝牙耳机，提供出色的音质和舒适的佩戴体验。",
    price: 299,
    image: "/placeholder.svg?height=400&width=400&text=蓝牙耳机",
    category: "electronics",
    categoryName: "电子产品",
    stock: 30,
  },
  {
    id: "3",
    name: "北欧风格台灯",
    description: "简约现代的北欧风格台灯，为您的家居增添温馨氛围。",
    price: 159,
    image: "/placeholder.svg?height=400&width=400&text=台灯",
    category: "home",
    categoryName: "家居",
    stock: 20,
  },
  {
    id: "4",
    name: "保湿面霜套装",
    description: "滋润保湿面霜套装，适合各种肤质，让肌肤水润光滑。",
    price: 259,
    image: "/placeholder.svg?height=400&width=400&text=面霜",
    category: "beauty",
    categoryName: "美妆",
    stock: 40,
  },
  {
    id: "5",
    name: "专业瑜伽垫",
    description: "防滑耐用的专业瑜伽垫，为您的健身提供舒适支持。",
    price: 129,
    image: "/placeholder.svg?height=400&width=400&text=瑜伽垫",
    category: "sports",
    categoryName: "运动",
    stock: 25,
  },
  {
    id: "6",
    name: "休闲牛仔裤",
    description: "经典款式的休闲牛仔裤，舒适耐穿，百搭易搭配。",
    price: 229,
    image: "/placeholder.svg?height=400&width=400&text=牛仔裤",
    category: "clothing",
    categoryName: "服装",
    stock: 35,
  },
  {
    id: "7",
    name: "智能手表",
    description: "多功能智能手表，支持心率监测、运动追踪等功能。",
    price: 599,
    image: "/placeholder.svg?height=400&width=400&text=智能手表",
    category: "electronics",
    categoryName: "电子产品",
    stock: 15,
  },
  {
    id: "8",
    name: "北欧风格抱枕",
    description: "柔软舒适的北欧风格抱枕，为您的沙发增添时尚元素。",
    price: 89,
    image: "/placeholder.svg?height=400&width=400&text=抱枕",
    category: "home",
    categoryName: "家居",
    stock: 45,
  },
]
